# Generated by Django 3.0.6 on 2021-01-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='hosting/files')),
                ('uri', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='hosting/images')),
                ('uri', models.CharField(max_length=1000)),
            ],
        ),
    ]
