# Generated by Django 3.0.6 on 2020-07-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='hosting/files')),
                ('uri', models.CharField(max_length=10000)),
            ],
        ),
    ]
