# Generated by Django 3.0.6 on 2020-05-29 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remote_addr', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=256)),
                ('path', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField(max_length=2048)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=32, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.ContactFormCategory')),
            ],
        ),
    ]
