# Generated by Django 3.0.6 on 2020-05-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformcategory',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
