# Generated by Django 3.0.6 on 2020-05-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200529_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='user_agent',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
