# Generated by Django 3.0.6 on 2020-06-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20200529_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
