# Generated by Django 3.0.6 on 2020-07-22 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20200608_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.ContactFormCategory'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
