# Generated by Django 3.0.6 on 2020-07-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20200722_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='path',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='remote_addr',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
