# Generated by Django 3.0.6 on 2020-06-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='profiles/none.png', null=True, upload_to='profiles'),
        ),
    ]
