# Generated by Django 3.0.6 on 2020-06-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20200618_1401'),
        ('profile', '0002_profile_pic'),
    ]

    operations = [
    ]
