# Generated by Django 3.0.6 on 2020-07-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_merge_20200621_1644'),
        ('profile', '0003_merge_20200620_1716'),
    ]

    operations = [
    ]
