# Generated by Django 3.0.6 on 2020-08-15 08:14

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Post category',
                'verbose_name_plural': 'Post categories',
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1400)),
                ('summary', models.TextField(blank=True, max_length=2000, null=True)),
                ('body', djrichtextfield.models.RichTextField(max_length=1048576)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('c', 'Review'), ('p', 'Publish')], default='d', max_length=1)),
                ('slug', models.SlugField(default='', editable=False, max_length=1400, unique=True)),
                ('thumbnail', models.ImageField(default='blog/none.png', max_length=1024, upload_to='blog/thumbnails', validators=[blog.models.validate_image_res])),
                ('priority', models.IntegerField(default=1)),
                ('read', models.IntegerField(default=1)),
                ('time', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.PostCategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='common.Tag')),
            ],
        ),
    ]
