# Generated by Django 3.0.6 on 2020-05-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('summary', models.TextField(max_length=2000)),
                ('text', models.TextField(max_length=1048576)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(default=None)),
                ('authors', models.ManyToManyField(to='user_auth.Author')),
            ],
        ),
    ]
