# Generated by Django 3.0.6 on 2020-05-28 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200528_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posttag',
            name='name',
            field=models.CharField(default=None, max_length=16),
            preserve_default=False,
        ),
    ]
