# Generated by Django 3.0.6 on 2020-05-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200529_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='read',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.IntegerField(default=1),
        ),
    ]
