# Generated by Django 3.0.6 on 2020-06-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('blog', '0010_auto_20200603_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='common.Tag'),
        ),
    ]
