# Generated by Django 3.0.6 on 2020-06-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200609_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='blog/none.png', max_length=1024, upload_to='blog/thumbnails'),
        ),
    ]
