# Generated by Django 3.0.6 on 2020-05-17 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(default='', max_length=140)),
                ('body', models.TextField(default='', max_length=10240)),
                ('origin_url', models.URLField(default=None)),
                ('internal_url', models.URLField(default=None)),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('published', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_auth.Author')),
                ('etype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='event.EventType')),
            ],
            options={
                'ordering': ('-starts_at',),
            },
        ),
    ]
