# Generated by Django 3.0.6 on 2021-01-01 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models
import event.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Etiket adı')),
            ],
            options={
                'verbose_name': 'etiket',
                'verbose_name_plural': 'etiketler',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Etkinlik türünün adı')),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'etkinlik türü',
                'verbose_name_plural': 'etkinlik türleri',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=640, verbose_name='Etkinliğin adı')),
                ('description', models.TextField(max_length=1400, null=True, verbose_name='Etkinliğin kısa açıklaması/özeti')),
                ('body', djrichtextfield.models.RichTextField(blank=True, null=True, verbose_name='Etkinliğin detaylı açıklaması')),
                ('slug', models.SlugField(default='', editable=False, max_length=64, unique=True)),
                ('origin_url', models.URLField(verbose_name='Etkinliğin resmi sitesi')),
                ('internal_url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.ImageField(default='thumbnails/none/placeholder.jpg', max_length=1024, upload_to='thumbnails', validators=[event.models.validate_image_res], verbose_name='Albüm kapağı')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Son başvuru tarihi')),
                ('starts_at', models.DateTimeField(verbose_name='Başlangıç tarihi')),
                ('ends_at', models.DateTimeField(verbose_name='Bitiş tarihi')),
                ('location', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Etkinliğin konumu')),
                ('prize', models.CharField(blank=True, max_length=200, null=True, verbose_name='Etkinlikte dağıtılacak toplam para ödülü')),
                ('priority', models.IntegerField(default=1, verbose_name='Öncelik (aksi söylenmedikçe 1 bırakın)')),
                ('holder', models.CharField(blank=True, max_length=200, null=True, verbose_name='Etkinliği düzenleyen kurum')),
                ('published', models.BooleanField(default=True, verbose_name='Yayınla')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.EventType', verbose_name='Etkinlik türü')),
                ('tags', models.ManyToManyField(related_name='events', to='common.Tag', verbose_name='Alakalı etiketler')),
            ],
            options={
                'verbose_name': 'etkinlik',
                'verbose_name_plural': 'etkinlikler',
                'ordering': ('priority', '-starts_at'),
            },
        ),
    ]
