# Generated by Django 3.0.6 on 2020-08-15 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models
import event.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=640)),
                ('description', models.TextField(max_length=1400, null=True)),
                ('body', djrichtextfield.models.RichTextField(blank=True, null=True)),
                ('slug', models.SlugField(default='', editable=False, max_length=64, unique=True)),
                ('origin_url', models.URLField()),
                ('internal_url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.ImageField(default='thumbnails/none/placeholder.jpg', max_length=1024, upload_to='thumbnails', validators=[event.models.validate_image_res])),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('prize', models.CharField(blank=True, max_length=200, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('holder', models.CharField(blank=True, max_length=200, null=True)),
                ('published', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.EventType', verbose_name='Event type')),
                ('tags', models.ManyToManyField(related_name='events', to='common.Tag')),
            ],
            options={
                'ordering': ('-starts_at',),
            },
        ),
    ]
