# Generated by Django 3.0.6 on 2020-09-21 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='etype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.EventType', verbose_name='Etkinlik türü'),
        ),
    ]
