# Generated by Django 3.0.6 on 2020-05-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200517_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='internal_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
