# Generated by Django 3.0.6 on 2020-05-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='origin_url',
            field=models.URLField(),
        ),
    ]
