# Generated by Django 3.0.6 on 2020-05-23 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_event_holder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_online',
        ),
    ]
