# Generated by Django 3.0.6 on 2020-05-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20200524_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/none/placeholder.jpg', max_length=1024, upload_to='thumbnails'),
        ),
    ]
