# Generated by Django 3.0.6 on 2020-06-03 15:29

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=64, unique=True),
        ),
    ]
