# Generated by Django 3.0.6 on 2020-06-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('event', '0016_auto_20200603_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(related_name='eventtag', to='common.Tag'),
        ),
    ]
