# Generated by Django 3.0.6 on 2020-06-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_auto_20200603_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='holder',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
