# Generated by Django 3.0.6 on 2020-06-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_auto_20200609_1753'),
        ('event', '0017_auto_20200605_1452'),
    ]

    operations = [
    ]
