# Generated by Django 3.0.6 on 2020-06-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_merge_20200609_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='holder',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
