# Generated by Django 3.0.6 on 2020-06-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_auto_20200609_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=1400, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='holder',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=640),
        ),
        migrations.AlterField(
            model_name='event',
            name='prize',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
