# Generated by Django 3.0.6 on 2020-06-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_auto_20200609_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtag',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
