# Generated by Django 3.0.6 on 2020-06-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('event', '0021_auto_20200609_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(related_name='events', to='common.Tag'),
        ),
    ]
