# Generated by Django 3.0.6 on 2020-05-17 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('origin_url', models.URLField(default=None)),
                ('internal_url', models.URLField(default=None)),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('duration', models.DurationField(default=None)),
                ('published', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_auth.Author')),
            ],
        ),
    ]
