# Generated by Django 3.0.6 on 2020-05-17 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_author_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_auth.Role'),
        ),
    ]
